name: Run Streamlit App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit requests pandas

      - name: Run Streamlit application
        run: |
          streamlit run ui.py --logger.level=debug
